User.create!(name:  "タイハムスター",
             email: "asadanaohisa8215@gmail.com",
             password:              "Asada82158215",
             password_confirmation: "Asada82158215",
             admin: true)

Category.create!([{:name => "キッチン用品"},
                  {:name => "バス用品"},
                  {:name => "ランドリー用品"},
                  {:name => "ボディケア用品"},
                  {:name => "スキンケア用品"},
                  {:name => "ヘアケア用品"},
                  {:name => "フェイスケア用品"},
                  {:name => "その他"}])

ChildCategory.create!([{:name => "たわし", :category_id => "1"},
                       {:name => "スポンジ", :category_id => "1"},
                       {:name => "キッチンペーパー", :category_id => "1"},
                       {:name => "サランラップ", :category_id => "1"},
                       {:name => "食器用洗剤", :category_id => "1"},
                       {:name => "アルミホイル", :category_id => "1"},
                       {:name => "その他", :category_id => "1"},
                       {:name => "風呂用洗剤", :category_id => "2"},
                       {:name => "ボディタオル", :category_id => "2"},
                       {:name => "入浴剤", :category_id => "2"},
                       {:name => "その他", :category_id => "2"},
                       {:name => "洗濯用洗剤", :category_id => "3"},
                       {:name => "柔軟剤", :category_id => "3"},
                       {:name => "漂白剤", :category_id => "3"},
                       {:name => "洗濯槽クリーナー", :category_id => "3"},
                       {:name => "その他", :category_id => "3"},
                       {:name => "ハンドソープ", :category_id => "4"},
                       {:name => "ボディソープ", :category_id => "4"},
                       {:name => "その他", :category_id => "4"},
                       {:name => "ハンドクリーム", :category_id => "5"},
                       {:name => "日焼け止めクリーム", :category_id => "5"},
                       {:name => "リップクリーム", :category_id => "5"},
                       {:name => "その他", :category_id => "5"},
                       {:name => "シャンプー", :category_id => "6"},
                       {:name => "コンディショナー", :category_id => "6"},
                       {:name => "ヘアカラー", :category_id => "6"},
                       {:name => "ワックス類", :category_id => "6"},
                       {:name => "ヘアスプレー", :category_id => "6"},
                       {:name => "その他", :category_id => "6"},
                       {:name => "洗顔フォーム", :category_id => "7"},
                       {:name => "メイク落とし", :category_id => "7"},
                       {:name => "クレンジングオイル", :category_id => "7"},
                       {:name => "化粧水", :category_id => "7"},
                       {:name => "乳液", :category_id => "7"},
                       {:name => "その他", :category_id => "7"},
                       {:name => "トイレットペーパ", :category_id => "8"},
                       {:name => "ティッシュペーパー", :category_id => "8"}])
